name: consuming_movie_api
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  dio: ^5.8.0+1
  easy_localization: ^3.0.7+1
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.2.1
  get: ^4.7.2
  pretty_dio_logger: ^1.4.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
